/**
 * Created by sunday on 02/11/2016.
 */
// Wechat Js Sign
export const FETCH_WECHATJSSIGN = 'FETCH_WECHATJSSIGN'
export const CLEAR_WECHATJSSIGN = 'CLEAR_WECHATJSSIGN'

// Home
export const FETCH_HOME = 'FETCH_HOME'
export const CLEAR_HOME = 'CLEAR_HOME'

// Auth
export const AUTH = 'AUTH'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

// User
export const FETCH_ME = 'FETCH_ME'
export const FETCH_INFO = 'FETCH_INFO'
export const CLEAR_USER = 'CLEAR_USER'

// Integral
export const FETCH_INTEGRALS = 'FETCH_INTEGRALS'
export const CLEAR_INTEGRAL = 'CLEAR_INTEGRAL'

// Coupons
export const FETCH_COUPONS = 'FETCH_COUPONS'
export const FETCH_COUPONS_INVALID = 'FETCH_COUPONS_INVALID'
export const CLEAR_COUPON = 'CLEAR_COUPON'

// Orders
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_CHANGE = 'FETCH_ORDERS_CHANGE'
export const FETCH_ORDERS_COUNT = 'FETCH_ORDERS_COUNT'
export const CLEAR_ORDERS = 'CLEAR_ORDERS'

// Tuans
export const FETCH_TUANS = 'FETCH_TUANS'
export const FETCH_TUANS_CHANGE = 'FETCH_TUANS_CHANGE'
export const FETCH_TUANS_COUNT = 'FETCH_TUANS_COUNT'
export const CLEAR_TUANS = 'CLEAR_TUANS'

// Cycles
export const FETCH_CYCLES = 'FETCH_CYCLES'
export const FETCH_CYCLES_CHANGE = 'FETCH_CYCLES_CHANGE'
export const FETCH_CYCLES_COUNT = 'FETCH_CYCLES_COUNT'
export const CLEAR_CYCLES = 'CLEAR_CYCLES'

// Redeem
export const FETCH_REDEEM_CODE = 'FETCH_REDEEM_CODE'
export const FETCH_REDEEM_GOODS = 'FETCH_REDEEM_GOODS'
export const FETCH_REDEEM_ADDRESS = 'FETCH_REDEEM_ADDRESS'
export const CLEAR_REDEEM = 'CLEAR_REDEEM'

// Recharge
export const FETCH_RECHARGES = 'FETCH_RECHARGES'
export const FETCH_RECHARGES_CHANGE = 'FETCH_RECHARGES_CHANGE'
export const FETCH_RECHARGES_AMOUNT = 'FETCH_RECHARGES_AMOUNT'
export const FETCH_RECHARGES_USECARD = 'FETCH_RECHARGES_USECARD'
export const CLEAR_RECHARGE = 'CLEAR_RECHARGE'

// Invite
export const FETCH_INVITES = 'FETCH_INVITES'
export const CLEAR_INVITE = 'CLEAR_INVITE'

// Address
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES'
export const FETCH_ADDRESSES_SETDEFAULT = 'FETCH_ADDRESSES_SETDEFAULT'
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS'

// Projects
export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECTS_TASTE = 'FETCH_PROJECTS_TASTE'
export const FETCH_PROJECTS_NEW = 'FETCH_PROJECTS_NEW'
export const FETCH_PROJECTS_BEST = 'FETCH_PROJECTS_BEST'
export const FETCH_PROJECTS_HOT = 'FETCH_PROJECTS_HOT'
export const CLEAR_PROJECT = 'CLEAR_PROJECT'

// Projects Sell Out
export const FETCH_PROJECTS_OUT = 'FETCH_PROJECTS_OUT'
export const FETCH_PROJECTS_OUT_TASTE = 'FETCH_PROJECTS_OUT_TASTE'
export const FETCH_PROJECTS_OUT_NEW = 'FETCH_PROJECTS_OUT_NEW'
export const FETCH_PROJECTS_OUT_BEST = 'FETCH_PROJECTS_OUT_BEST'
export const FETCH_PROJECTS_OUT_HOT = 'FETCH_PROJECTS_OUT_HOT'
export const CLEAR_PROJECT_OUT = 'CLEAR_PROJECT_OUT'

// Goods
export const FETCH_GOODS_PROJECT = 'FETCH_GOODS_PROJECT'
export const FETCH_GOODS_VOTES = 'FETCH_GOODS_VOTES'
export const FETCH_GOODS_PROGRESS = 'FETCH_GOODS_PROGRESS'
export const FETCH_GOODS_GOODS = 'FETCH_GOODS_GOODS'
export const FETCH_GOODS_COMMENTS = 'FETCH_GOODS_COMMENTS'
export const CLEAR_GOODS = 'CLEAR_GOODS'

// Comments
export const FETCH_COMMENTS_PROJECT = 'FETCH_COMMENTS_PROJECT'
export const FETCH_COMMENTS_LIST = 'FETCH_COMMENTS_LIST'
export const FETCH_COMMENTS_REPLY = 'FETCH_COMMENTS_REPLY'
export const FETCH_COMMENTS_ZAN = 'FETCH_COMMENTS_ZAN'
export const CLEAR_COMMENT = 'CLEAR_COMMENT'

// vote
export const FETCH_VOTE_COMMENTS_PROJECT = 'FETCH_VOTE_COMMENTS_PROJECT'
export const FETCH_VOTE_COMMENTS = 'FETCH_VOTE_COMMENTS'
export const FETCH_VOTE_COMMENTS_REPLY = 'FETCH_VOTE_COMMENTS_REPLY'
export const FETCH_VOTE_COMMENTS_ZAN = 'FETCH_VOTE_COMMENTS_ZAN'
export const CLEAR_VOTE_COMMENT = 'CLEAR_VOTE_COMMENT'

